"""Offline manual blueprint; never an importable Retell workflow."""
import json
from config.settings import ROOT
from src.manual_retell.business_rules import read,save
VARIABLES={}
def vars(category,names,setters,readers,purpose,clear,required='Conditional'):
 for name in names.split():VARIABLES[name]={'category':category,'purpose':purpose.get(name,name.replace('_',' ')),'set_by':setters.split(),'read_by':readers.split(),'required':required,'clear_when':clear}
vars('Caller','caller_name caller_phone caller_email','01 07 08','01 07 08 09',{'caller_phone':'Callback with consent only; not verification','caller_email':'Optional callback/enrollment contact; not verification'},'End call under approved retention; never public logs','Optional')
vars('Student','student_name student_or_parent age','01 02 03 04','01 02 03 04 05 06 07',{'age':'Explicit student age; do not infer from package','student_or_parent':'student / parent / other'},'Student changes: clear licensing, verification, package and tentative slots')
vars('Licensing','first_time_applicant license_status learner_license_status permit_status driver_education_status parent_taught_status texas_residency_status out_of_state_license_status foreign_license_status impact_texas_status road_test_eligibility','02','02 03 04 05 06',{'permit_status':'Compatibility view of learner_license_status; update together','out_of_state_license_status':'Derived from license_status and jurisdiction','foreign_license_status':'Derived from license_status and jurisdiction','road_test_eligibility':'unknown / prerequisites_reported / needs_review; never government-approved'},'Student/age/credential changes; requalify affected pathway')
vars('Licensing details','license_issuing_jurisdiction license_expiry learner_issue_date certificate_type required_document_status impact_program impact_certificate_date move_date suspension_during_hold','02','02 04 05',{},'Changed credential/student; ask only if applicable reviewed rule needs it')
vars('Intent','primary_intent secondary_intent active_persona previous_persona resume_goal','01 02 03 04 05 06 07 08','01 02 03 04 05 06 07 08 09',{'primary_intent':'Current semantic action goal','secondary_intent':'Deferred explicit goal','active_persona':'Current node ID','previous_persona':'Saved valid prior node ID','resume_goal':'Minimal suspended task and dependencies'},'New call; consume completed detour; explicit new goal changes primary intent','Required')
vars('Sales','program course_id course_name package_id package_name package_price recommended_service currency price_snapshot experience_level','03 04 05','01 02 03 04 05 06 09',{'package_id':'Canonical catalog ID, never provisional form ID','package_price':'Numeric catalog base price, caller cannot overwrite','price_snapshot':'Reviewed catalog source/version','experience_level':'Caller-reported confidence and training goal'},'Package changes clear session plan and tentative availability; preserve unrelated verified existing booking')
vars('Booking','preferred_location preferred_date preferred_time session_count_required session_plan available_slots selected_slot selected_sessions appointment_id booking_status booking_version','06','03 04 05 06 07 08 09',{'preferred_location':'Caller area preference, not operational ID or pickup commitment','preferred_date':'Caller-confirmed ISO date in agreed school timezone','session_plan':'Ordered minute durations from known business plan; observation separate','session_count_required':'Known derived driving count; null for unresolved PTDE/preparation','available_slots':'Ephemeral returned observations; never static knowledge','selected_slot':'Returned authoritative object; never fabricate an ID from a label','selected_sessions':'Ordered tentative selections with duration/provenance','appointment_id':'Verified backend result only, not caller-entered reference','booking_status':'Guarded enum in booking_state_machine.md','booking_version':'Backend concurrency version; mock version synthetic'},'Date/location/package/resource changes invalidate tentative slots; expire according to approved backend freshness, no invented TTL')
vars('Booking guards','location_id school_timezone adapter_mode last_tool_result production_write_enabled backend_success_verified booking_reference_input verified_customer_ref request_id idempotency_key tool_failure_count pending_action','06','06 07 08 09',{'location_id':'Authoritative operational ID only; unknown today','school_timezone':'Owner/backend-confirmed IANA string; unknown in current payload','adapter_mode':'Builder-set demo_mock / production_safe','production_write_enabled':'Secure server configuration; false today','backend_success_verified':'Server-derived explicit correct-environment success and appointment ID gate','booking_reference_input':'Caller-reported known reference; not verified appointment identity','verified_customer_ref':'Scoped secure identity; no credentials/tokens in conversation state','last_tool_result':'Sanitized normalized result including mode/confirmation/error','request_id':'Server-issued non-PII trace ID','idempotency_key':'Server-issued same-action retry key','pending_action':'create / find / reschedule / cancel / none'},'New action/context clears success/result/key; preserve in-flight action and key on interruption until reconciled')
vars('Support','support_issue support_category verification_status escalation_reason','06 07 08','06 07 08 09',{'support_issue':'Minimal caller symptom, not verified account facts','support_category':'faq / instruction / booking_change / access / payment / certificate / account / high_risk','verification_status':'unverified / verified / failed; secure system sets verified','escalation_reason':'Specific reason staff needed; not proof ticket or transfer occurred'},'Student/customer changes clear verification; new issue resets reason/category')
vars('Source control','knowledge_snapshot','00','01 02 03 04 05 06 07 08 09',{'knowledge_snapshot':'Reviewed business/regulatory source version and freshness gate'},'Builder changes reviewed source set; never caller-controlled','Required')
NODES=[]
def node(id,name,file,type,purpose,entry,reads,writes,questions,strategy,sources,success,fallback,tests,tools=''):
 NODES.append(dict(id=id,name=name,file=file,type=type,purpose=purpose,entry_conditions=entry,reads=reads.split(),writes=writes.split(),questions=questions,strategy=strategy,knowledge_sources=sources,success_criteria=success,fallback=fallback,tests=tests.split(),tools=tools.split()))
node('00','Global Agent Rules','global_agent_rules','Global settings (conceptual node)','One consistent Best Driving School employee voice and safe actions','Applies throughout; not a routable conversation node','knowledge_snapshot adapter_mode production_write_enabled','knowledge_snapshot',[],
 'Represent Best Driving School. Speak briefly, conversationally, one or two relevant questions at a time. Allow interruptions; do not repeatedly use names, lecture or re-ask answered facts. Check shared state first. Never invent prices, packages, licensing rules, availability, appointments, student data, policy, refund or payment results. Use reviewed school data for business and DPS/TDLR records for regulations; suppress disputed/review-required records. CTO scheduling rules are internal business rules only. Confirm operations only after explicit correct-environment backend success and returned appointment identity. Every mock result must be described as a demo reservation. Caller statements are reported, not verified. Do not collect passwords, cards, DOB, permit/document numbers or authentication tokens in conversational state. Escalate unavailable writes, private issues, unknown policy, regulatory edge cases and repeated failures.',
 'knowledge/retell_support/regulatory_response_guardrails.md; data/structured/package_catalog.json; data/structured/internal_business_scheduling_rules.json','Source-grounded answers and no premature action claim','Any unresolved safety/capability issue → 08','T11 T12 T17 T18')
node('01','Greeting / Main Router','router_node','Conversation','Semantic intent classification with minimal clarification','Start call or explicit unrelated goal switch','primary_intent secondary_intent age package_id support_issue previous_persona resume_goal','primary_intent secondary_intent active_persona previous_persona resume_goal age student_or_parent',
 ['Thanks for calling Best Driving School. How can I help?','Practice request with unknown age: How old is the student?','Ambiguous price/location: Which service are you considering?'],
 'Classify goals by meaning, not keyword presence. First-time Texas licensing uncertainty → 02 before sales. Clear adult education/lessons → 03; teen/parent or parent-taught service → 04; road test → 05; availability/new/existing booking/reschedule/cancel → 06; paid course/account support → 07. Pricing follows relevant sales; location follows selected service or Booking, distinguishing advertised areas from branches/pickup. Do not perform full sales qualification. Ask one useful clarification, then staff if still unresolved. Politely redirect off-topic once; avoid endless loops.',
 'knowledge/retell_support/router_intent_reference.md; knowledge/locations.md','Correct specialist with minimum sufficient context','Unresolved intent or human request → 08; caller done → 09','T01 T03 T07 T13 T17')
node('02','Texas License Guide','texas_license_guide_node','Conversation','Determine pathway before inappropriate selling','Licensing uncertainty, jurisdiction edge or missing prerequisite',
 'age first_time_applicant license_status learner_license_status permit_status driver_education_status parent_taught_status texas_residency_status out_of_state_license_status foreign_license_status impact_texas_status road_test_eligibility license_issuing_jurisdiction license_expiry learner_issue_date certificate_type required_document_status impact_program impact_certificate_date move_date suspension_during_hold previous_persona resume_goal knowledge_snapshot',
 'first_time_applicant license_status learner_license_status permit_status driver_education_status parent_taught_status texas_residency_status out_of_state_license_status foreign_license_status impact_texas_status road_test_eligibility license_issuing_jurisdiction license_expiry learner_issue_date certificate_type required_document_status impact_program impact_certificate_date move_date suspension_during_hold active_persona previous_persona resume_goal',
 ['Age only if unknown; first-time applicant only if relevant','Current learner license or other driver license?','Ask jurisdiction, residency or education stage next only as pathway needs it'],
 'Use progressive questions, not the entire checklist. Identify adult/teen/new-resident/international/parent-taught branch from reported facts. Retrieve applicable reviewed pathway/rule conditions; give one plain-language next step. Distinguish education, instruction, practice, skills test and DPS issuance. Do not guarantee government eligibility or transfer/provider acceptance. Changed age/credential invalidates dependent qualification. Return to saved goal after resolution. Advice does not require a purchase. Suppress disputed and review-required details.',
 'knowledge/regulatory/README.md; knowledge/regulatory/adult_first_time_license.md; knowledge/regulatory/teen_license_pathway.md; knowledge/regulatory/new_texas_residents.md; knowledge/regulatory/international_drivers.md; knowledge/regulatory/parent_taught_driver_education.md; knowledge/retell_support/regulatory_response_guardrails.md',
 'Supported usual pathway explained; eligibility remains reported or needs_review','Unverified edge/conflict → 08 with official DPS/TDLR referral','T01 T06 T19')
node('03','Adult Sales Specialist','adult_sales_node','Conversation','Match adult education/lesson needs to actual catalog options','Clear adult service goal or appropriate adult pathway',
 'age driver_education_status license_status permit_status experience_level program course_id course_name package_id package_name package_price currency price_snapshot recommended_service knowledge_snapshot',
 'program course_id course_name package_id package_name package_price currency price_snapshot recommended_service experience_level active_persona',
 ['Education course, hands-on lessons, or both, if unclear?','What would you like to improve behind the wheel?','Offer one grounded option and ask preference before selection'],
 'Distinguish six-hour online education from private lessons; adult age alone does not imply mandatory education. Use catalog and goal/budget to compare appropriate options; no readiness guarantee. Explain sourced base price and known hours; mention separate sourced processing fee when relevant, no invented total. Adult 2/4/6/8/10 hours imply 1/2/3/4/5 two-hour CTO sessions. Sales explains hours; Booking owns dates. Online education has secure official enrollment/access, no timed booking. Price challenge triggers catalog check, never caller overwrite.',
 'data/structured/package_catalog.json; knowledge/adult_services.md; data/structured/internal_business_scheduling_rules.json','Valid package chosen or informed decision without pressure','Licensing uncertainty → 02; current price conflict → 08; schedule → 06','T02 T08 T12')
node('04','Teen Sales Specialist','teen_sales_node','Conversation','Match teen stage and parent-taught context safely','Teen/parent education or driving-support goal',
 'age student_or_parent driver_education_status learner_license_status parent_taught_status program course_id course_name package_id package_name package_price currency price_snapshot recommended_service knowledge_snapshot',
 'program course_id course_name package_id package_name package_price currency price_snapshot recommended_service active_persona',
 ['Parent or student, if unknown?','What education and in-car instruction is already completed?','Parent-taught program or school-led instruction, if unclear?'],
 'Use safety-first tone. Compare full education and behind-the-wheel only from catalog. Clarify partial education/certificate stage without inventing transfer acceptance. Parent-taught practice support does not replace the approved program or all training. Both known teen packages have seven actual driving hours: CTO plan [120,120,120,60], four driving sessions. Do not apply this plan to seven observation hours or classroom/cohort timing. Load prices, contents and labels from catalog. Generated reference: full package $399, 24 classroom + 7 driving + 7 observation, Best selling; BTW $350, 7 driving + 7 observation. These are snapshot illustrations, not independent price sources.',
 'data/structured/package_catalog.json; knowledge/teen_services.md; knowledge/parent_taught.md; data/structured/internal_business_scheduling_rules.json','Stage-appropriate valid package with limitations clear','Licensing → 02; transfer/observation/PTDE allocation unknown → 08; schedule → 06','T03 T04 T09 T12')
node('05','Road Test Sales Specialist','road_test_sales_node','Conversation','Qualify test intent and compare test-only versus useful preparation','Road-test intent or qualified test pathway',
 'age road_test_eligibility learner_license_status driver_education_status impact_texas_status experience_level program course_id course_name package_id package_name package_price currency price_snapshot knowledge_snapshot',
 'program course_id course_name package_id package_name package_price currency price_snapshot recommended_service experience_level active_persona',
 ['Road test itself, if intent unclear?','Missing prerequisite understanding only','Would practice beforehand help, or do you only want the test?'],
 'Use reviewed prerequisites, not confidence as verified eligibility. Compare actual catalog test-only and preparation/test options. Offer preparation for expressed skill need, never pressure a ready caller. CTO allocation: 30-minute slot, actual service 20 minutes. Reset/buffer details remain internal unless relevant/asked. Preparation duration remains unknown; do not assign test or standard lesson duration to preparation. Booking validates actual starts against confirmed schedule origin/resources.',
 'data/structured/package_catalog.json; knowledge/road_test.md; knowledge/regulatory/road_test_requirements.md; data/structured/internal_business_scheduling_rules.json','Appropriate choice and prerequisite understanding; no oversell','Prerequisites unclear → 02; critical preparation/allocation unknown → 08; ready schedule → 06','T05 T06 T10')
node('06','Booking & Scheduling Specialist','booking_node','Subagent (tool-capable dialogue, manually gated tools)','Own availability, selection and guarded appointment operations','Availability/new/existing booking/change/cancel; new timed appointment requires selected package',
 'package_id package_name package_price age road_test_eligibility preferred_location preferred_date preferred_time session_count_required session_plan available_slots selected_slot selected_sessions appointment_id booking_status booking_version location_id school_timezone adapter_mode last_tool_result production_write_enabled backend_success_verified booking_reference_input verified_customer_ref verification_status request_id idempotency_key tool_failure_count pending_action previous_persona resume_goal',
 'preferred_location preferred_date preferred_time session_count_required session_plan available_slots selected_slot selected_sessions appointment_id booking_status booking_version location_id last_tool_result backend_success_verified booking_reference_input verified_customer_ref verification_status request_id idempotency_key tool_failure_count pending_action escalation_reason active_persona previous_persona resume_goal',
 ['Missing package, area, date or time preference only; resolve relative date with caller','Known existing booking reference, if absent; never enumerate accounts','Before future action: confirm package, returned location, dates/times and durations; get clear approval'],
 'Use booking_state_machine.md. Derive known business session plan. PRODUCTION-SAFE today: approved read-only check_availability offers provisional observations only; unknown stable slot IDs/timezone/resources prevents binding selection. New booking/find/change/cancel require staff. DEMO: synthetic only, label before any action and every confirmation; synthetic customer/verification fixtures belong in test harness, never real identity. FUTURE: package → session plan → verified location/timezone → fresh compatible returned slots → choices → caller selection → critical approval → authenticated create → wait for explicit correct-environment backend success and appointment IDs. Multi-session atomicity/remaining-hour accounting require contracts; track tentative choices and per-session confirmed outcomes separately. Road starts must follow confirmed backend 30-minute origin; never round contradictory observed labels. Race: briefly apologize, refresh, offer returned choices. Read retry at most once if useful, then staff. Write timeout means unknown outcome; preserve key and reconcile before retry. Verify scoped customer/reference and concurrency version before lookup/change/cancel. No production action is available simply because its name appears in this blueprint.',
 'data/structured/session_rules.json; data/structured/scheduling_models.json; docs/availability_contract.md; docs/retell_booking_tool_contracts.md; knowledge/retell_support/booking_state_reference.md',
 'Reads never confirm booking; real confirmation requires authorized explicit production success and identity; mock confirmation always demo','Unavailable write/verification/lookup, alignment gap, unknown policy or repeated failure → 08; licensing → 02; account → 07','T07 T08 T09 T10 T11 T14 T15 T20','check_availability create_booking find_booking reschedule_booking cancel_booking')
node('07','Existing Student Support','student_support_node','Conversation','Triage support without inventing private records','Paid course, account, certificate or support issue',
 'support_issue support_category verification_status verified_customer_ref booking_reference_input appointment_id package_id previous_persona resume_goal',
 'support_issue support_category escalation_reason booking_reference_input active_persona previous_persona resume_goal',
 ['Minimal symptom: what happens when you try to access the course?','Course/service only if unknown; no password or card details'],
 'Classify public FAQ, instruction, booking change, access, payment, certificate, account or high risk. Public FAQ/instruction uses reviewed knowledge; booking change → 06. Private issues require approved authenticated support tool or staff; none exists now. Do not claim payment received, active enrollment, issued certificate, refund or reset from caller statement. Parent role does not verify account authority. Do not collect credentials or promise ticket submission.',
 'knowledge/faq.md; knowledge/policies.md; knowledge/retell_support/unresolved_information.md','Public issue answered or minimal issue/reason routed to staff','Private/access/payment/certificate/account or unknown policy → 08','T16 T20 T21')
node('08','Human Escalation','human_escalation_node','Conversation (transfer only if later verified/configured)','Explain staff need and verified next step','Human requested or safe automation unavailable',
 'escalation_reason support_issue support_category package_id preferred_date booking_reference_input caller_name caller_phone caller_email adapter_mode pending_action last_tool_result',
 'escalation_reason caller_name caller_phone caller_email active_persona',
 ['Would you like the verified school contact information?','Callback details only with consent and an actual configured intake'],
 'Set specific reason: write/lookup unavailable, payment/refund dispute, account access, uncertain policy, regulatory edge, failure or human request. Briefly explain why staff is needed. No transfer/CRM/ticket integration exists. Offer verified published school contact from reviewed knowledge; confirm contact/hours before deployment, never invent them. A future transfer/intake must acknowledge success before saying connected or sent. No callback promise without accepted intake. Preserve minimal context, avoid private records. Caller declines → 09.',
 'knowledge/locations.md; knowledge/business_overview.md; knowledge/policies.md','Caller knows unresolved action and actual next step; no fake transfer','Contact unavailable: acknowledge need without guessing; close politely','T18 T20 T21')
node('09','End Call','end_call_node','End (short final utterance)','Close with an accurate essential outcome','Caller finished or escalation next step agreed',
 'booking_status appointment_id backend_success_verified adapter_mode last_tool_result escalation_reason pending_action package_name support_issue','active_persona',[],
 'Summarize only essential confirmed outcome, no full recap. A real appointment statement requires BOOKING_CONFIRMED, appointment_id and explicit authorized production success; demo always labeled demo. Cancelled result is not active reservation. Unresolved booking/payment/account action remains unresolved; no claimed callback or submission. Pending write outcome is unknown and needs reconciliation. End naturally without repeated questions.',
 'knowledge/retell_manual/booking_state_machine.md','Short truthful ending','Human request returns to 08; otherwise state next action clearly','T11 T18 T20')
EDGES=[]
def edge(a,b,c):EDGES.append({'from':a,'to':b,'condition':c,'context_rule':'Preserve answered caller/student/licensing and catalog state. For temporary detour set previous_persona/resume_goal; consume on return and clear/revalidate stale dependent slots.'})
for b,c in [('02','First-time Texas/licensing uncertainty'),('03','Clear adult education/lessons'),('04','Teen/parent or parent-taught service'),('05','Road-test service'),('06','Availability/new/existing booking/change/cancel'),('07','Existing student issue'),('08','Human request or unresolved route'),('09','Caller done')]:edge('01',b,c)
for b,c in [('03','Adult pathway resolved; relevant service requested'),('04','Teen pathway resolved; relevant service requested'),('05','Prerequisites reported; test option requested'),('06','Return to saved booking goal after qualification'),('09','Advice answered; no sale wanted')]:edge('02',b,c)
for a in ['03','04','05']:
 edge(a,'06','Valid timed package chosen and caller wants schedule');edge(a,'02','Licensing prerequisite uncertainty');edge(a,'09','Information complete or self-paced secure enrollment next step explained')
for a,b,c in [('06','02','Eligibility question/uncertainty'),('06','07','Account/course support emerges'),('06','09','Observation or confirmed correct-mode result complete'),('07','06','Booking change'),('07','09','Public FAQ answered'),('08','09','Verified next step offered or caller declines')]:edge(a,b,c)
for a in ['02','03','04','05','06','07']:
 edge(a,'01','Explicit unrelated new goal; route semantically');edge(a,'08','Human requested, private/unknown policy, unavailable action or repeated failure')
STATES='NO_PACKAGE PACKAGE_SELECTED AVAILABILITY_NEEDED AVAILABILITY_CHECKED SLOT_OPTIONS_PRESENTED SLOT_SELECTED SESSIONS_PARTIALLY_SELECTED ALL_SESSIONS_SELECTED BOOKING_PENDING BOOKING_CONFIRMED BOOKING_FAILED HUMAN_ESCALATION'.split()
STATE_EDGES=[('NO_PACKAGE','PACKAGE_SELECTED','Valid catalog selection'),('PACKAGE_SELECTED','AVAILABILITY_NEEDED','Known requirement and fresh slots needed'),('AVAILABILITY_NEEDED','AVAILABILITY_CHECKED','Successful correct-mode read; no confirmation'),('AVAILABILITY_CHECKED','SLOT_OPTIONS_PRESENTED','Describe returned observations and limitations'),('SLOT_OPTIONS_PRESENTED','SLOT_SELECTED','Caller selects returned authoritative compatible slot; current live labels cannot satisfy this gate'),('SLOT_SELECTED','SESSIONS_PARTIALLY_SELECTED','Fewer than required multi-session choices'),('SESSIONS_PARTIALLY_SELECTED','ALL_SESSIONS_SELECTED','All compatible tentative choices; not booked'),('SLOT_SELECTED','BOOKING_PENDING','Single session approval + verified customer + ready backend contract + authorized environment'),('ALL_SESSIONS_SELECTED','BOOKING_PENDING','Approval and verified transaction semantics; no assumed atomicity'),('BOOKING_PENDING','BOOKING_CONFIRMED','EXPLICIT_BACKEND_SUCCESS: correct-mode success AND returned appointment ID(s) AND booking_confirmed=true. Real confirmation additionally production_write_enabled=true AND backend_success_verified=true; mock always demo.'),('BOOKING_PENDING','BOOKING_FAILED','Explicit negative backend result; timeout remains pending reconciliation'),('BOOKING_FAILED','AVAILABILITY_NEEDED','Race: clear stale slot, refresh and obtain new choice')]
for s in STATES[:-1]:STATE_EDGES.append((s,'HUMAN_ESCALATION','Capability unavailable, private access, alignment/policy gap or repeated failure'))
SCENARIOS=[]
def scenario(id,title,start,questions,vs,route,tools,outcome):SCENARIOS.append(dict(id=id,title=title,starting_node=start,questions=questions,variables=vs.split(),transitions=route,tools=tools.split(),expected_outcome=outcome,execution_status='DESIGN ONLY — manual call not run'))
scenario('T01','Adult first-time, 19, unsure where to start','01','Do not re-ask age; current credential/education, residency as needed','age first_time_applicant license_status driver_education_status','01 → 02 → 03 or 09','','Reviewed usual pathway; no mandatory purchase invented')
scenario('T02','Adult permit and nervous driver','01','Age if missing, skill/confidence goal','age permit_status experience_level package_id','01 → 03 → 06','check_availability','Appropriate catalog lesson comparison, no readiness guarantee or real booking')
scenario('T03','Parent with daughter 15','01','Education/learner stage, not supplied age again','age student_or_parent driver_education_status','01 → 04 → 02 if needed','','Teen path, no immediate road-test promise')
scenario('T04','Teen partial education elsewhere','01','Completed stage/certificate category, age if missing','age driver_education_status certificate_type parent_taught_status','01 → 04 → 02 or 08','','No inferred transfer acceptance; BTW only if suitable')
scenario('T05','Ready driver wants test only','01','Only missing prerequisites','road_test_eligibility package_id','01 → 05 → 06','check_availability','Test-only if appropriate; no pressured preparation or real reservation')
scenario('T06','Test soon, cannot parallel park or prerequisites unclear','01','Confidence and prerequisite gap','experience_level road_test_eligibility','01 → 05 → 02 or 08','','Reasonable preparation option; no guaranteed eligibility')
scenario('T07','Saturday afternoon availability','01','Missing service/date; resolve relative date in agreed timezone','preferred_date preferred_time package_id available_slots booking_status','01 → 06 → 09 or 08','check_availability','Approved provisional read only; no static knowledge or reservation')
scenario('T08','Adult six-hour multi-session','03','Missing preferences; discuss three tentative sessions','package_id session_count_required session_plan selected_sessions booking_status','03 → 06 → 08 production / 09 demo','check_availability create_booking','[120,120,120]; separate per-session outcomes, no assumed atomic school booking')
scenario('T09','Teen seven-hour driving','04','Driving dates separate from observation allocation','session_count_required session_plan selected_sessions','04 → 06 → 08 production','check_availability','[120,120,120,60], four driving sessions; observation not converted')
scenario('T10','Road-test interval with contradictory live labels','05','Preferred date; keep buffers internal','package_id selected_slot booking_status','05 → 06 → 08','check_availability','20+5+5=30 business rule; no rounded/fabricated starts; verify backend origin')
scenario('T11','Move Tuesday appointment to Thursday','01','Known reference; future secure verification, no private enumeration','booking_reference_input verification_status pending_action','01 → 06 → 08 production / 09 demo','find_booking check_availability reschedule_booking','Production unavailable; demo verified and version-checked, no early success')
scenario('T12','Teen price challenge: I thought it was $299','04','Which teen package only if ambiguous','package_id package_price price_snapshot','04 → 04 or 08','','Catalog check: full snapshot $399, BTW $350; never overwrite from caller claim')
scenario('T13','Mid-call adult sales to existing test reschedule','03','Existing reference only if missing','primary_intent previous_persona resume_goal booking_reference_input','03 → 01 → 06','find_booking','Preserve context; no repeated age/package question; staff fallback today')
scenario('T14','Slot taken after selection','06','Refresh choices and obtain new selection','selected_slot available_slots booking_status last_tool_result','06 → 06 or 08','create_booking check_availability','SLOT_NO_LONGER_AVAILABLE; never success or blind retry')
scenario('T15','Tool timeout/API failure','06','One useful read retry, no repeated writes','tool_failure_count pending_action request_id idempotency_key','06 → 08','check_availability create_booking','Write timeout outcome unknown; preserve key/reconcile; read retry at most once')
scenario('T16','Paid online course inaccessible','01','Minimal symptom and course, no password/card','support_category support_issue escalation_reason','01 → 07 → 08','','No payment/enrollment/account assertion; staff required')
scenario('T17','Off-topic or unclear caller','01','One brief school-service clarification','primary_intent escalation_reason','01 → 01 → 08 or 09','','Polite redirect, no invented service/endless loop')
scenario('T18','Human explicitly requested','03','Reason optional, no forced sales qualification','escalation_reason','03 → 08 → 09','','Immediate staff path; no transfer/callback claim without acknowledgement')
scenario('T19','Foreign credential edge or contradictory age','02','Country/validity/residency categories; resolve contradiction','license_issuing_jurisdiction license_status age road_test_eligibility','02 → 08','','Reviewed rule only; no exemption invented')
scenario('T20','Cancel and refund request','01','Known reference, reason optional','pending_action booking_reference_input verification_status escalation_reason','01 → 06 → 08 production / 09 demo','find_booking cancel_booking','Real cancel/refund blocked; synthetic cancellation releases fixtures, no refund implied')
scenario('T21','Certificate/account issue, parent caller','07','Issue category, no private record disclosure','support_category verification_status escalation_reason','07 → 08','','Parent relationship not verified authority; no certificate/account assertions')
def write(path,text):
 p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text,encoding='utf-8')
def heading(title):return '# '+title+'\n\nManual design documentation only. No Retell agent, workflow, state or tools have been created or modified.\n\n'
def tool_text(n):
 if n['id']=='06':return 'Normalized check_availability, create_booking, find_booking, reschedule_booking, cancel_booking. Demo: synthetic mock through a future test wrapper. Production-safe: approved read-only availability only; lookup/writes blocked. Nothing wired into Retell today. Permissions enforced server-side, never by caller prompt.'
 return 'None; knowledge-only dialogue. Human node may use a transfer/intake only after verified manual configuration and explicit tool acknowledgement; none exists today.' if n['id']=='08' else 'None; knowledge-only dialogue.'
def details(n):
 fields=[('Purpose',n['purpose']),('Entry conditions',n['entry_conditions']),('Node type',n['type']),('Prompt blueprint / response strategy',n['strategy']),('Read variables',', '.join('`'+v+'`' for v in n['reads'])),('Write variables',', '.join('`'+v+'`' for v in n['writes'])),('Required information / questions','Before asking, check populated state; ask again only to resolve contradiction or confirm critical action.\n\n'+'\n'.join('- '+q for q in n['questions']) if n['questions'] else 'No mandatory questions; check known state first.'),('Knowledge sources',n['knowledge_sources']),('Tools',tool_text(n)),('Exit / success criteria',n['success_criteria']),('Transitions and conditions','\n'.join('- NODE '+e['to']+': '+e['condition'] for e in EDGES if e['from']==n['id']) or 'Global configuration applies to all nodes; no routable edge.'),('Failure behavior / human handoff',n['fallback']),('Interrupt handling','Stop speaking on interruption. Distinguish clarification, temporary detour and changed goal. Preserve answered context; save previous_persona/resume_goal for detour. Preserve pending_action/request_id/idempotency_key and reconcile before conflicting action.'),('Test cases',', '.join(n['tests']))]
 return ''.join('## '+k+'\n\n'+v+'\n\n' for k,v in fields)
def main():
 catalog={p['package_id']:p for p in read('data/structured/package_catalog.json')}
 full=catalog['teen_24_hr_classroom_driving_package']['current_price'];btw=catalog['teen_behind_the_wheel_only_7_7']['current_price']
 # Illustrative prices in rendered prompts/tests come from the same catalog.
 for n in NODES:n['strategy']=n['strategy'].replace('full package $399',f'full package ${full:g}').replace('BTW $350',f'BTW ${btw:g}')
 for s in SCENARIOS:s['expected_outcome']=s['expected_outcome'].replace('full snapshot $399',f'full snapshot ${full:g}').replace('BTW $350',f'BTW ${btw:g}')
 save('data/design/manual_retell_blueprint.json',{'artifact_type':'offline_validation_schema_not_retell_workflow','nodes':NODES,'variables':VARIABLES,'handoffs':EDGES,'booking_states':STATES,'booking_state_transitions':[{'from':a,'to':b,'guard':c} for a,b,c in STATE_EDGES],'scenarios':SCENARIOS,'modes':{'demo_mock':'Synthetic only; transaction mechanics, no real reservation','production_safe':'Approved reads only, default disabled; lookup and writes blocked'}})
 for n in NODES:write('knowledge/retell_manual/'+n['file']+'.md',heading('NODE '+n['id']+' — '+n['name'])+details(n))
 t=heading('Shared state — final recommended dictionary')+'Unset values are null/unknown. Reported licensing facts are not verified account facts. Optional contact is not needed for advice/prices. No passwords, cards, DOB, document numbers or verification tokens. Compatibility aliases have one source of truth: permit_status mirrors learner_license_status; foreign/out-of-state views derive from license and jurisdiction. Legacy intent → primary_intent, selected_package → package_id, texas_resident_status → texas_residency_status, previous_intent → resume_goal, selected_slot_id → selected_slot.slot_id.\n\n'
 for category in dict.fromkeys(v['category'] for v in VARIABLES.values()):
  t+='## '+category+'\n\n| Variable | Purpose | Set by NODE | Read by NODE | Required | Clear when |\n| --- | --- | --- | --- | --- | --- |\n'
  for key,v in VARIABLES.items():
   if v['category']==category:t+=f'| `{key}` | {v["purpose"]} | {", ".join(v["set_by"])} | {", ".join(v["read_by"])} | {v["required"]} | {v["clear_when"]} |\n'
  t+='\n'
 t+='## Types, defaults and trust\n\nIDs/names/contact nullable strings; age integer; first_time_applicant nullable boolean; licensing/intent/support values precise categories. Prices numeric USD, source read-only. Dates ISO YYYY-MM-DD. session_plan ordered minute integers; selected_sessions ordered tentative slot/duration/provenance objects; available_slots ephemeral list. school_timezone owner-confirmed IANA string. Defaults: verification_status=unverified, booking_status=NO_PACKAGE, tool_failure_count=0, backend_success_verified=false, production_write_enabled=false. Server/configuration owns adapter_mode, timezone, verified IDs, versions, request keys, permissions and explicit success; the model must not set them from caller claims. Although NODE 06 consumes these values, its writes are restricted to validated tool/state events.\n\nChanging student clears licensing/verification/sales/tentative booking context. Changing package clears tentative session/slot selections, not a separate verified existing appointment. Temporary detours preserve tentative context only; revalidate when returning. End call cleanup follows approved retention; no private state in public knowledge.\n'
 write('knowledge/retell_manual/shared_state.md',t)
 t=heading('Persona handoff matrix')+'Priority: human request/safety → 08; reconcile pending operation before conflicting action; explicit new goal → Router; qualification → relevant specialist; completion → End. Resolve competing conditions by priority. Do not announce bot transfers; bridge naturally.\n\n| From | To | Condition | Context |\n| --- | --- | --- | --- |\n'
 for e in EDGES:t+=f'| NODE {e["from"]} | NODE {e["to"]} | {e["condition"]} | {e["context_rule"]} |\n'
 t+='\nReturn to saved task via Router only after caller agrees; saved destination must be 02–07. Consume completed detour to prevent immediate retrigger. Adult Sales → Router → Booking for existing reschedule; Booking → License Guide → Booking for eligibility; Road Sales → License Guide → Road Sales when prerequisites resolved. Preserve valid context and invalidate dependent stale slots.\n'
 write('knowledge/retell_manual/handoff_matrix.md',t)
 t=heading('Booking state machine')+'State is guarded, not free-text model confidence.\n\n| From | To | Guard |\n| --- | --- | --- |\n'
 for a,b,c in STATE_EDGES:t+=f'| {a} | {b} | {c} |\n'
 t+='\nOnly BOOKING_PENDING → BOOKING_CONFIRMED can confirm, with EXPLICIT_BACKEND_SUCCESS. Availability, selection, native form submission, caller payment claim or timeout cannot satisfy it. Current production_write_enabled=false prevents all real confirmation. Mock requires mode=mock, synthetic=true, production=false and MOCK appointment identity; spoken confirmation always demo reservation. Cancelled result has booking_confirmed=false, not an active reservation.\n\nWrite timeout stays pending/outcome unknown; preserve same action key and reconcile before retry. Explicit failure becomes BOOKING_FAILED; race refreshes availability and gets a new selection. Date/location/package changes return to AVAILABILITY_NEEDED. Multi-session partial successes record only confirmed appointment IDs and escalate remaining work; never silently cancel already-confirmed sessions or claim all confirmed.\n\nLookup: known reference → secure scoped verification → backend find → verified identity. Reschedule: lookup/version → fresh compatible slots → caller approval → atomic replacement → explicit result; old reservation stays until success. Cancel: scoped verification + approved policy + caller confirmation → backend cancel → explicit cancelled status. Refund is distinct and unimplemented. All production lookup/change/cancel currently escalate.\n'
 write('knowledge/retell_manual/booking_state_machine.md',t)
 t=heading('Persona prompt blueprints')+'Apply NODE 00 globally. Keep separate node prompts; do not concatenate into one giant prompt.\n\n'
 for n in NODES[1:]:
  t+='## NODE '+n['id']+' — '+n['name']+'\n\n'
  for k,v in [('Role',n['name']+' as the same Best Driving School employee'),('Primary goal',n['purpose']),('Conversation strategy',n['strategy']),('Knowledge allowed',n['knowledge_sources']),('Tools allowed',tool_text(n)),('Required information',', '.join(n['reads'])+'; ask only relevant missing fields'),('Questions','; '.join(n['questions']) or 'No mandatory question'),('Prohibited behavior','No invented facts/actions, no static slots, no private credentials, no re-asking answered facts. No real confirmation from mock, selection or timeout.'),('Success criteria',n['success_criteria']),('Transition conditions','; '.join(e['to']+': '+e['condition'] for e in EDGES if e['from']==n['id'])),('Fallback behavior',n['fallback']),('Tone','Short, calm, conversational and interruption-friendly; never speak node/endpoint details')]:t+='**'+k+':** '+v+'\n\n'
 write('knowledge/retell_manual/persona_prompt_blueprints.md',t)
 t=heading('Manual Retell build checklist')+'Build order: 1 global rules; 2 state; 3 Router; 4 License Guide; 5 Adult Sales; 6 Teen Sales; 7 Road Sales; 8 Booking; 9 Support; 10 Human; 11 End; 12 transitions; 13 isolated mock/approved read-only wiring; 14 test calls. No production writes.\n\nUI mapping checked 2026-09-13: [Retell flow overview](https://docs.retellai.com/build/conversation-flow/overview) describes global settings, dialogue nodes, tool-capable Subagent nodes, deterministic Function nodes and End nodes. [Global-node guide](https://docs.retellai.com/build/conversation-flow/global-node) describes transitions from anywhere and return conditions. Verify available UI before manual build. NODE 00 is global settings, not an extra routable node.\n\n'
 for n in NODES:
  t+='## NODE '+n['id']+' — '+n['name']+'\n\n'
  for k,v in [('Node name',n['name']),('Node type',n['type']),('Prompt',n['file']+'.md and persona_prompt_blueprints.md section'),('Variables read',', '.join(n['reads'])),('Variables written',', '.join(n['writes'])),('Tools',tool_text(n)),('Transition conditions','; '.join(e['to']+': '+e['condition'] for e in EDGES if e['from']==n['id']) or 'Applies globally'),('Fallback transition',n['fallback']),('Interrupt handling','Enable supported barge-in; preserve context, save detour, reconcile pending tool before new action'),('End conditions',n['success_criteria'])]:t+='- [ ] '+k+': '+v+'\n'
  t+='\n'
 t+='## Integration acceptance\n\n- [ ] Bind only reviewed specialist sources; suppress review-required regulatory records.\n- [ ] Configure defined state types/clearing and catalog-owned prices; backend guards must not rely on free-text extraction.\n- [ ] Deploy approved authenticated wrapper before tool wiring; current adapters are not HTTP services.\n- [ ] Keep synthetic mock separate from production; secure verification and credentials stay server-side.\n- [ ] Omit or hard-reject production lookup/create/reschedule/cancel; allow only approved read adapter.\n- [ ] Validate timezone, stable IDs, duration/resource compatibility and road-test schedule origin before future binding actions.\n- [ ] Optional deterministic Function utility nodes may be added after real API contracts exist; no speculative tools.\n- [ ] Verify contact/hours and actual transfer/intake acknowledgement before enabling human tools.\n- [ ] Run all planned calls, record actual pass/fail and recordings. No executed calls claimed here.\n'
 write('knowledge/retell_manual/retell_build_checklist.md',t)
 t=heading('Manual test-call matrix')+'Expected outcomes only, not executed calls. Covers the original assignment’s mandatory challenges plus multi-session/remainder/road-allocation checks. Human builders must record at least 14 actual call results and three demo recordings (sales→booking, booking/reschedule, support/recovery) after manual deployment.\n\n'
 for s in SCENARIOS:
  t+='## '+s['id']+' — '+s['title']+'\n\n'
  for k in ['starting_node','questions','variables','transitions','tools','expected_outcome','execution_status']:t+='**'+k.replace('_',' ').title()+':** '+(', '.join(s[k]) if isinstance(s[k],list) else s[k])+'\n\n'
  t+='**Actual result / recording / pass-fail:** Pending manual build.\n\n'
 write('knowledge/retell_manual/test_matrix.md',t)
 sessions={p['package_id']:p for p in read('data/structured/session_rules.json')}
 t=heading('Generated catalog reference')+'Generated from canonical catalog; refresh reviewed source at build time. This is an illustration, not a second maintained price source.\n\n| Package ID | Name | Base USD | Driving plan minutes |\n| --- | --- | --- | --- |\n'
 for p in read('data/structured/package_catalog.json'):t+=f'| {p["package_id"]} | {p["package_name"]} | {p["current_price"]:.2f} | {sessions[p["package_id"]].get("session_plan_minutes","Not established / not applicable")} |\n'
 write('knowledge/retell_manual/catalog_reference.md',t)
 extra='\n## Multi-session UX and implementation limits\n\nAdult six hours: Session 1, Session 2, Session 3, each 120 minutes. Teen seven driving hours: Sessions 1–3 120 minutes, Session 4 60 minutes. Ask dates/times per session only as future backend supports; permit pause/resume without repeated preferences. All-at-once transaction, independent remaining-session booking and hours tracking remain unverified. Record each confirmed identity separately; tentative choices do not imply partial booking. Never cancel confirmed sessions automatically after a later failure.\n\nExisting mock has four synthetic one-hour slot fixtures, not school duration/accounting rules. It demonstrates five transaction mechanics. A future duration-aware test wrapper/fixture is required for faithful lesson-duration demonstrations; do not change CTO rules to match fixture length. Current tools are planning contracts, none connected in Retell.\n\nFuture wrapper must map canonical IDs to verified native identities, validate slot duration/resources/timezone and road-test origin, enforce server-owned state/mode permissions and provide idempotency/versions. Use raw observed GET paths only in developer availability_contract.md, never customer prompts. A 30-minute road allocation contains 20 service + 5 reset + 5 buffer; do not generate a conceptual grid as available capacity. Preparation and observation scheduling remain distinct and unresolved.\n'
 p=ROOT/'knowledge/retell_manual/booking_node.md';p.write_text(p.read_text(encoding='utf-8')+extra,encoding='utf-8')
 t=heading('Manual Retell visual flow')+'NODE 00 global configuration applies throughout. Diagram is documentation, not a workflow import; complete edge conditions are in handoff_matrix.md.\n\n```mermaid\nflowchart TD\n START([Start]) --> N01[01 Greeting / Router]\n N01 --> N02[02 Texas License Guide]\n N01 --> N03[03 Adult Sales]\n N01 --> N04[04 Teen Sales]\n N01 --> N05[05 Road Test Sales]\n N01 --> N06[06 Booking]\n N01 --> N07[07 Student Support]\n N02 <--> N03\n N02 <--> N04\n N02 <--> N05\n N02 <--> N06\n N03 --> N06\n N04 --> N06\n N05 --> N06\n N06 <--> N07\n N06 --> N08[08 Human Escalation]\n N07 --> N08\n N02 --> N08\n N03 --> N08\n N04 --> N08\n N05 --> N08\n N01 --> N08\n N08 --> N09[09 End Call]\n N06 --> N09\n N07 --> N09\n N01 --> N09\n```\n\nExplicit changed goals reroute through 01 from specialists; temporary detours preserve shared context and revalidate slots on return. Human request takes priority. Demo confirmations stay synthetic; production-safe reads are provisional and writes go to staff. Diagram edges do not imply deployed APIs.\n'
 write('docs/manual_retell_flow.md',t)
 t=heading('Best Driving School — master manual Retell build specification')+'## Scope and readiness\n\nPrimary Phase D deliverable. Ten conceptual nodes: NODE 00 global settings plus nine flow nodes. No Retell agent/workflow/API mutation or import. Business rules verified by CTO; backend enforcement unverified. Current Python adapters are not deployed HTTP endpoints. Follow ../knowledge/retell_manual/retell_build_checklist.md build order and UI mapping.\n\n## Modes and tool boundary\n\nDEMO: all five mechanics use isolated synthetic mock through a future authenticated test wrapper. Current mock fixtures do not validate school lesson durations; duration-aware fixtures are needed for faithful multi-session demonstration. PRODUCTION-SAFE: approved read-only availability, disabled by default; no lookup or writes. Expose current limitations to callers. No payment/account/refund/transfer tool exists.\n\nFuture wrapper must enforce verified customer scope, canonical-to-native mapping, returned compatible slots/timezone/resources, caller approval, concurrency/idempotency and explicit environment-aware success. Prompt language alone cannot authorize a transaction or set success. Use docs/retell_booking_tool_contracts.md inputs/outputs; credentials/verification tokens stay server-side. Do not expose raw endpoint paths in customer prompts.\n\n## Business rules and state\n\nStandard driving sessions 120 minutes, final shorter remainder. Known teen seven driving hours: [120,120,120,60], four sessions; observation separate. Road service/reset/buffer 20/5/5 within 30-minute allocation. Retain conflicting frontend labels and validate backend origin; never round/fabricate slots. PTDE practice-hour names do not establish instructor plans.\n\nshared_state.md defines every variable and clearing rule. booking_state_machine.md defines guarded actions; handoff_matrix.md defines all transitions. Routing priority: human/safety, pending-action reconciliation, explicit goal switch, qualification/service action, completion. Preserve previous_persona/resume_goal only for a caller-approved temporary detour and consume after return. Revalidate stale selections.\n\n## Node specifications\n\n'
 for n in NODES:t+='## NODE '+n['id']+' — '+n['name']+'\n\n'+details(n).replace('## ','### ')+(extra if n['id']=='06' else '')
 t+='## Acceptance and manual QA\n\nUse all per-node checklists and 21 expected-call scenarios. Capture actual results and at least three recordings only after manual build. No executed voice-call results claimed here. Review no repeated questions, price overwrite, static slot knowledge, premature action confirmation or private account disclosure. Production writes remain blocked until backend/business contracts close the documented gaps.\n'
 t+='\n## Manual tool-wrapper mapping\n\nFuture wrapper design only, not deployed school endpoints. Model-facing inputs are canonical package/preferences, returned slot IDs or a known caller reference. Secure wrapper injects verified customer_ref/verification_token into adapter calls; tokens never appear in shared conversation state. Server creates request/idempotency keys and controls modes/permissions.\n\ncheck_availability passes package_id, preferred_date and location_id=null for current live reads, returns booking_confirmed=false and never invents slot IDs/timezone. Demo create passes package_id, slot_ids, synthetic verified customer/token and idempotency_key. Find first verifies scoped known reference; caller booking_reference_input is not an appointment_id. Reschedule uses verified identity/version plus returned slot_ids and expected_version. Cancel uses scoped identity/version and clear caller approval; refund separate. All production lookup/writes remain blocked.\n\nWrapper maps adapter mock to demo_mock and live_read_only to production_safe. Future production success mapping is a proposed reviewed contract, not an observed school response. can_confirm is offline design validation, not deployed authorization. No HTTP wrapper or tools wired in Retell.\n'
 write('docs/retell_manual_build_spec.md',t)
 p=ROOT/'knowledge/retell_support/data_source_matrix.md';s=p.read_text(encoding='utf-8');marker='## Phase C.1 / D authority matrix';s=s.split('\n'+marker)[0]
 s+='\n'+marker+'\n\n| Information | Authority | Treatment |\n| --- | --- | --- |\n| Package price/contents | Best Driving School catalog website snapshot | Reviewed business facts, not caller-editable |\n| Texas eligibility | Reviewed DPS/TDLR records | Regulatory; suppress disputed rules |\n| Driving duration/remainder | CTO / INTERNAL BUSINESS RULE | BUSINESS VERIFIED, enforcement unverified |\n| Road 20+5+5 / 30 allocation | CTO / INTERNAL BUSINESS RULE | BUSINESS VERIFIED; frontend conflict preserved |\n| Available time | Approved live read endpoint | Ephemeral observation, not reservation |\n| Selected preference | Caller input | Tentative |\n| Confirmed booking | Authorized explicit backend success + appointment ID | Environment-aware guard |\n| Student account | Scoped authenticated system | Unavailable today; staff |\n| Mock result | Synthetic adapter | Demo only |\n'
 p.write_text(s,encoding='utf-8')
 stats=dict(nodes=len(NODES),shared_variables=len(VARIABLES),transitions=len(EDGES),persona_blueprints=len(NODES)-1,test_scenarios=len(SCENARIOS));save('reports/phase_d_design_counts.json',stats)
 t=heading('Phase D design review')+'\n'.join('- '+k.replace('_',' ')+': '+str(v) for k,v in stats.items())+'\n\n## Conclusions\n\nComplete required manual documentation; architecture preserves understand → route → qualify → recommend → select package → check availability → act → recover → escalate with one employee voice. NODE 00 global configuration; Booking tool-capable dialogue; other specialists knowledge-only. No Retell changes, import or production tool connection. Platform mapping checked against official [Retell overview](https://docs.retellai.com/build/conversation-flow/overview) and [global-node guide](https://docs.retellai.com/build/conversation-flow/global-node); humans must verify their UI.\n\n## Remaining gates\n\nAuthenticated wrapper/deployment; server-owned state and confirmation guards; duration-aware synthetic fixtures; authoritative IDs/timezone/resources; transaction/remaining-session accounting; scoped customer verification; payment/refund/cancel/pickup policy; actual transfer/intake and verified contact. All 21 scenarios are expected outcomes, not call results. Required original-assignment actual call results/recordings remain manual QA work.\n\n## Preservation\n\nOriginal four Phase C structured files archived; website evidence and regulatory data unchanged. CTO rules labeled INTERNAL BUSINESS RULE / BUSINESS VERIFIED, never DPS/TDLR. Frontend conflict retained, backend enforcement false. No static availability in blueprint knowledge.\n'
 write('reports/phase_d_retell_design_review.md',t);print(json.dumps(stats))
if __name__=='__main__':main()
