"""Assemble operational findings from preserved frontend and read-only evidence."""
import json
from bs4 import BeautifulSoup
from config.settings import ROOT
from src.utils import write_json,write_text,digest


def read(path):return json.loads((ROOT/path).read_text(encoding='utf-8'))


def main():
    packages=read('data/structured/package_catalog.json');metadata=read('data/structured/page_metadata.json')
    pages={m['url']:m for m in metadata};backend=[];locations=[];models=[];sessions=[];forms=[]
    for p in packages:
        m=pages[p['source']['url']];soup=BeautifulSoup((ROOT/m['raw_html']).read_bytes(),'lxml')
        form=soup.select_one('main [data-enroll-form]');product=None;blocks=None
        if form:
            inputs=form.select('input[name=product_id]')
            chips=soup.select('[data-pk-chip]')
            chip=next((c for c in chips if c.get('data-value')==p['package_name']),None)
            token=chip.get('data-enroll-chip') if chip else None
            field=next((i for i in inputs if i.get('value')==token),None) if token else inputs[0] if len(inputs)==1 else None
            if field:product=field.get('value');blocks=field.get('data-blocks')
        evidence={'source_url':m['url'],'raw_html':m['raw_html'],'content_hash':m['content_hash'],
                  'selector':'main [data-enroll-form] input[name=product_id]',
                  'scope':'Server-rendered public frontend; no backend database/schema access'}
        path=form.get('data-enroll-api') if form else None
        backend.append({'package_id':p['package_id'],'public_name':p['package_name'],
            'internal_identifiers':{'product_id':product,'course_id':None,'service_id':None,'schedule_id':None},
            'identifier_scope':'Observed form product_id, NOT independently verified stable backend identifier',
            'backend_authoritative_identifier_verified':False,'locations':[],
            'observed_availability_path':path,
            'location_specific_ids':None,'evidence':[evidence] if form else [],
            'verification_status':'partially_verified' if product else 'unknown'})
        online=not p['requires_live_availability'];adult=p['program_id']=='adult_driving';road=p['program_id']=='road_test';full=p['package_id'].startswith('teen_24')
        model='self_paced_external_access' if online else 'frontend_multi_row_appointment_selection' if adult else 'frontend_date_time_test_selection' if road else 'frontend_cohort_enrollment_then_schedule' if full else 'frontend_enrollment_without_visible_appointment_rows'
        note='Adult selected product controls 1–5 rows; every session says two hours. Server acceptance/remaining sessions unverified.' if adult else 'One date/time field for both road-test variants; practice duration and resource coupling unverified.' if road else 'class_code selects dated classroom batch; in-car and observation allocation unverified.' if full else 'No visible date/time fields in saved PTDE/BTW form despite teen availability API attribute; enrollment and later scheduling require confirmation.' if not online else 'No local enrollment form. External portal/access link appears; account activation/payment not traversed.'
        models.append({'package_id':p['package_id'],'schedulable':not online,'scheduling_model':model,
            'model_scope':'Observed frontend only','backend_enforcement_verified':False,
            'verification_status':'partially_verified','notes':note,'evidence':[evidence],
            'frontend_date_gap_days':int(form['data-enroll-date-gap']) if form and form.get('data-enroll-date-gap') else None})
        sessions.append({'package_id':p['package_id'],
            'total_hours':p['included']['driving_hours'] if adult else p['included']['practice_hours'] if p['program_id']=='parent_taught' else None,
            'purchased_components':{k:p['included'][k] for k in ('classroom_hours','driving_hours','observation_hours','practice_hours')},
            'session_duration_minutes':120 if adult else None,
            'expected_session_count':int(blocks) if adult and blocks else None,
            'frontend_block_count':int(blocks) if blocks else None,
            'frontend_block_count_is_not_confirmed_session_count':not adult,
            'observation_hours':p['included']['observation_hours'],'observation_booking_method':None,
            'session_duration_fixed_backend':None,'independent_sessions_supported':None,
            'all_sessions_booked_at_once':None,'frontend_collects_all_rows_before_submit':True if adult else None,
            'remaining_sessions_tracked':None,'rescheduling_supported':None,'cancellation_supported':None,
            'evidence':[evidence,{'path':'data/operational_evidence/enroll.js','section':'showRows and loadTimes'}],
            'status':'partially_verified' if not online else 'human_confirmation_required'})
        locations.append({'package_id':p['package_id'],'delivery':'online' if online else 'in_person',
            'locations':[{'location_id':None,'location_name':name,'role':'advertised_school_location' if name=='Plano' else 'advertised_service_area',
                'available':None,'operationally_verified':False} for name in ['Plano','Allen','Frisco','McKinney']] if not online else [],
            'location_parameter_observed':False,'pickup_address_parameter_observed':False,
            'verification_status':'partially_verified','evidence':[evidence]})
        if form:
            forms.append({'package_id':p['package_id'],'method':form.get('method','get').upper(),
                'action':form.get('action'),'availability_path':path,
                'field_names':sorted({i.get('name') for i in form.select('input,select') if i.get('name') and i.get('type') not in ('hidden','password')}),
                'fields_are_not_a_verified_write_api_contract':True,'submitted':False,'evidence':evidence})
    for name,value in [('package_backend_map',backend),('package_location_map',locations),('scheduling_models',models),('session_rules',sessions)]:write_json(ROOT/f'data/structured/{name}.json',value)
    write_json(ROOT/'data/operational_evidence/form_contracts_redacted.json',forms)
    # An integrity baseline for this phase's additive scope, not a freshness claim.
    baseline={str(p.relative_to(ROOT)).replace('\\','/'):digest(p.read_bytes()) for p in list((ROOT/'knowledge/regulatory').glob('*'))+list((ROOT/'data/structured').glob('*regulatory*.json'))+[(ROOT/'data/structured/package_catalog.json')] if p.is_file()}
    if not (ROOT/'reports/phase_c_preservation_hashes.json').exists():write_json(ROOT/'reports/phase_c_preservation_hashes.json',baseline)
    render(packages,backend,models,sessions,forms)
    print(json.dumps({'packages':13,'schedulable':12,'frontend_product_ids_observed':sum(bool(b['internal_identifiers']['product_id']) for b in backend),
                      'backend_authoritative_ids_verified':0,'frontend_adult_session_models_verified':5,'production_ready':0}))


def render(packages,backend,models,sessions,forms):
    header='Investigation date: 2026-09-13. Frontend observations, public date/time reads and backend-authoritative facts are distinguished. No private account or write workflow was traversed.\n\n'
    coverage='| Package | Schedulable? | Backend ID known? | Location known? | Session model known? | Availability method known? | Booking method known? | Production ready? |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n'
    for p,b,s in zip(packages,backend,sessions):
        coverage+=f'| {p["package_name"]} | {p["requires_live_availability"]} | Form product {b["internal_identifiers"]["product_id"] or "unknown"}; backend stability unverified | IDs unknown; Plano school/service areas advertised | '+('Adult two-hour rows (frontend)' if s['session_duration_minutes'] else 'Partial/unknown')+f' | {b["observed_availability_path"] or "No timed form"} | Payment form only; booking creation unverified | NO |\n'
    executive='Thirteen packages remain intact; 12 use scheduling. All 12 schedulable options have observed form product_id values, but 0/12 have independently verified stable backend identifiers. Three date-based GET availability paths are confirmed in frontend code and read successfully without authentication (road: 27 time labels; adult: empty; teen: five on one date). Five adult products control one–five two-hour appointment rows. No production booking, lookup, reschedule, cancellation or payment transaction was performed. A disabled-by-default read-only adapter and a synthetic mock provide separate capabilities.\n\n'
    text='# Phase C booking investigation\n\n'+header+executive+coverage+'\n'
    sections={
      'Package Mapping':'Observed product_id values: teen full 1, teen BTW 3, road only 4, practice/test 5, PTDE 10h 8/15h 7/30h 6, adult 2–10h 10–14. Online analytics item_id 15 is not a verified purchase identifier. Course/service/schedule IDs and location-dependent identity are unknown. See package_backend_map.json.',
      'Location Mapping':'One public school/testing location in Plano is advertised. Allen, Frisco and McKinney are service areas; no internal location IDs or location selector appears in the inspected forms/availability requests. Operational locations independently verified: zero. Do not create four branches in the adapter.',
      'Session Model':'Adult five variants collect one–five rows and the live form explicitly states each session is two hours. Switching from two to four hours reveals a second row. Date changes clear subsequent rows and constrain the next date at least one day later in frontend JS. Backend enforcement, independent remaining-session booking and tracking remain unknown. PTDE all three products carry data-blocks=7, but saved forms expose no matching appointment rows; never equate these with purchased 10/15/30 hours. Teen full uses class_code for a classroom cohort; in-car/observation scheduling is unverified.',
      'Availability':'Observed routes: GET /api/appointment-times, /api/adult-appointment-times, /api/teen-appointment-times with date only; Accept application/json and no-store in JS. Anonymous read replays returned HTTP 200 arrays. JS also accepts object values. No product, location, examiner, vehicle or customer parameter is sent by this frontend flow. Dates/time labels are ephemeral observations, not static capacity guarantees. Timezone, stable slot IDs and resource meaning are unknown. Road ranges observed were 15 minutes; this is not proof of total test/practice service duration.',
      'Booking':'The form declares POST https://bestdrivingschool.us/product/index/payment. It collects enrollment/contact details and appointment selections before Submit, with a notice that payment/total review is on the next screen. No POST was sent; whether it creates an enrollment, provisional hold or booking is unknown. Production write adapter methods are hard-disabled.',
      'Lookup':'UNKNOWN — ENDPOINT NOT YET CONFIRMED. No booking/customer enumeration. Proposed normalized lookup is limited to a verified customer and a known appointment reference; actual school verification/reference mechanisms require authorized access.',
      'Reschedule':'UNKNOWN — ENDPOINT NOT YET CONFIRMED. Proposed safe flow: verified lookup → availability → customer selection → atomic reschedule with version checks → explicit backend success. Only mock implements this; school support/cutoffs are unknown.',
      'Cancellation':'UNKNOWN — ENDPOINT NOT YET CONFIRMED. HUMAN ESCALATION REQUIRED for production. No refund or cancellation cutoff inferred from the 3% non-refundable processing charge. Mock cancellation releases synthetic slots and changes mock status only.',
      'Payment':'PARTIAL: dates may be selected in the public road/adult form before the declared payment POST, but adult marketing says pay then pick times. Preserve the sequence ambiguity. Checkout/payment/access activation/temporary reservations/webhooks remain unknown. Online education has no local form and an external access link; enrollment/account activation was not observed. No card data handled.',
      'Fees':'Public pages advertise a separate 3% non-refundable online processing charge. No checkout was submitted and no final-total calculation, tax, deposit or rounding rule was observed. Do not report base×1.03 as a confirmed payable total.',
      'Pickup / Dropoff':'Street address fields are contact/address collection, not proof of pickup. No pickup-specific selector, coverage radius or fee was verified. Package-specific pickup/dropoff requires owner confirmation; see pickup_dropoff_findings.md.',
      'Security':'Public read-only date/time endpoints were accessed without tokens or cookies intentionally supplied. F12 did not expose a raw network panel through the available browser control; endpoint/status/body shape are evidenced by frontend JS plus one read replay per route, not falsely labeled as captured DevTools traffic. No authentication/CSRF bypass. Logs retain field names and time labels only, never session/customer/driver/payment values.',
      'Missing Access':'Application routes/controllers/database schema, approved backend documentation/sandbox, customer-verification mechanism, transaction lifecycle, appointment identity, resource allocation, cancellations/refunds and checkout totals are unavailable in this repository. Owner-provided documentation or a synthetic sandbox account is needed for safe write-flow investigation.',
      'Retell Readiness':'Common interface specs and failure/state rules are ready for manual planning. Live adapter performs only evidenced GET availability and cannot create/find/change bookings. Default live disabled; enable explicitly via constructor only for approved read-only use. Mock supports synthetic create/find/reschedule/cancel with verification, slot races, atomic replacement and idempotency. Nothing is configured in Retell. Production custom functions are not ready until identifier, verification and transactional gaps close.'}
    for title,body in sections.items():text+=f'## {title}\n\n{body}\n\n'
    write_text(ROOT/'reports/phase_c_booking_investigation.md',text)
    text='# Booking network observations\n\n'+header+'Evidence labels: JS/form declaration, browser-visible UI, and anonymous read-only replay. A raw DevTools request capture was unavailable; no headers/cookies are fabricated.\n\n| Action | Method | Endpoint | Request fields | Response fields | Authentication observed | State changing? | Read-only safe? | Evidence |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n'
    for route,name,count in [('appointment-times','Road test date selected',27),('adult-appointment-times','Adult dates contract',0),('teen-appointment-times','Teen/PTDE declared times contract',5)]:
        text+=f'| {name} | GET | /api/{route} | date | array of time labels ({count} for one date); object-value fallback in JS | None required for read replay | No state change observed/intended; date-time query only | Yes, isolated time-only response | enroll.js loadTimes, form data-enroll-api, sanitized read evidence |\n'
    text+='| Enrollment/payment transition (NOT EXECUTED) | POST declaration | /product/index/payment | Public form field names, product_id and appointment fields as applicable; personal values omitted | UNKNOWN | Auth/CSRF/server validation UNKNOWN | Potential enrollment/payment/booking changes | NO | Preserved form action; Submit was not clicked |\n\nNo lookup/reschedule/cancel request was observed. Required headers from JS: Accept application/json; other browser headers/cookies not recorded. Read replay status: 200 for each GET; redirect/auth behavior beyond that single read is unknown. No query-grid enumeration.\n'
    write_text(ROOT/'reports/booking_network_observations.md',text)
    capabilities=[('package identification','PARTIALLY VERIFIED','Frontend product IDs; stable database mapping unknown'),('location identification','REQUIRES HUMAN CONFIRMATION','One advertised Plano site; all IDs/resource scopes unknown'),('availability lookup','PARTIALLY VERIFIED','Three GET paths/time-only arrays; no stable slot/resource IDs or timezone'),('session duration','PARTIALLY VERIFIED','Five adult frontend products: two-hour sessions'),('multi-session behavior','PARTIALLY VERIFIED','Adult row count/clearing shown; backend persistence unknown'),('booking creation','REQUIRES BUSINESS ACCESS','Payment form action is not a verified create API'),('booking lookup','NOT FOUND','No endpoint or verified identity mechanism'),('rescheduling','MOCK REQUIRED','School capability unknown'),('cancellation','MOCK REQUIRED','Production human escalation; refund rules unknown'),('payment relationship','PARTIALLY VERIFIED','Pre-submit dates versus pay-then-pick marketing ambiguity'),('processing fees','PARTIALLY VERIFIED','Public 3%; actual checkout calculation unknown'),('pickup/dropoff','REQUIRES HUMAN CONFIRMATION','Address is not pickup proof'),('student verification','REQUIRES BUSINESS ACCESS','Actual reference/authentication rules unknown')]
    text='# Booking gap analysis\n\n'+header+'| Capability | Status | Gap |\n| --- | --- | --- |\n'+''.join(f'| {a} | {b} | {c} |\n' for a,b,c in capabilities)+'\n'+coverage
    text+='\nNext: obtain official backend contracts and a synthetic sandbox. Confirm product IDs/location/resource mapping, multi-session accounting and transactional success semantics, then implement writes in a separate approved phase. Credentials must be configured only after the actual authentication scheme is known. No guessed credential keys or API paths were added.\n'
    write_text(ROOT/'reports/booking_gap_analysis.md',text)
    write_text(ROOT/'reports/pickup_dropoff_findings.md','# Pickup / dropoff findings\n\n'+header+'Public enrollment forms collect street_address, city, state and zip_code as contact/address fields. They do not identify these as pickup instructions. No package-specific pickup field, coverage radius, additional pickup fee or operational routing rule was confirmed. Plano is the advertised school/testing site; other cities are service areas. UNKNOWN — BUSINESS CONFIRMATION REQUIRED. Do not promise pickup or use a home address to infer it.\n')
    docs(sections)


def docs(sections):
    common='Design date: 2026-09-13. OUR NORMALIZED INTERFACE — not a claim about school endpoints or a Retell import.\n\n'
    write_text(ROOT/'docs/availability_contract.md','# Availability contract\n\n'+common+'Method: `check_availability(package_id, preferred_date, location_id=null)`. Package/date are required by our adapter; the school frontend sends only `date`. Canonical package selects an evidenced route internally. An internal location ID is unconfirmed, so live mode rejects a supplied location_id. Date format is ISO YYYY-MM-DD. No customer data is required for the observed availability read.\n\nOutput: success, mode, package_id, available_slots and booking_confirmed=false. Each normalized time has date/start_time/end_time/backend_time_label; slot_id=null, timezone=null, bookable_through_this_adapter=false. Empty array is successful empty availability; malformed/unavailable responses are errors. An object response is interpreted by its values exactly as the frontend does, then sorted/deduplicated. Never fabricate a stable slot ID from the displayed time.\n\nLive route lookup is allowlisted to the three observed time endpoints. No product/location/date-range/resource parameters are guessed. No redirect following or raw internal response exposure. Production creation must wait for authoritative slot/booking identity and timezone confirmation. Mock uses explicit MOCK-SLOT/MOCK-LOCATION fixtures with synthetic times, not those live labels.\n')
    write_text(ROOT/'docs/retell_booking_tool_contracts.md','# Future booking tool contracts\n\n'+common+'All responses include `success`, `mode` and `booking_confirmed`. Errors include safe `error_code`/`user_safe_message`; no internal traces or customer/session secrets. `mode=mock` additionally marks synthetic=true, production=false.\n\n| Operation | Our required inputs | Optional/conditional | Server-generated output | School contract status |\n| --- | --- | --- | --- | --- |\n| check_availability | package_id, preferred_date | location_id only once authoritative mapping exists; currently null in live | normalized time labels; real slot ID unavailable | Three date-only GET time routes evidenced |\n| create_booking | package_id, selected slot_ids, verified customer_ref, verification_token, idempotency_key | Multiple slots according to approved package rules; contact/enrollment fields later require explicit policy | appointment_id, booking_status, version | UNKNOWN; synthetic mock only |\n| find_booking | appointment_id, verified customer_ref, verification_token | Phone/email lookup only if approved non-enumerating verification contract is later documented | Verified minimal booking summary | UNKNOWN; synthetic mock only |\n| reschedule_booking | appointment_id, selected slot_ids, verified customer_ref, verification_token, expected_version | Apply confirmed business cutoff/session rules | Updated booking/version | UNKNOWN; synthetic mock only |\n| cancel_booking | appointment_id, verified customer_ref, verification_token, expected_version | Apply approved cancellation authorization; refund is separate | Cancelled status/version | UNKNOWN; synthetic mock only |\n\nCustomer_ref/verification_token are our proposed verified-session references, not claims that the school API has those fields. In mock they must be the pre-provisioned MOCK-CUSTOMER/VERIFY fixtures; no real names/contact/DOB records are accepted by the mock interface. Actual public payment form names are preserved separately without values; they are NOT implemented as a create API. Required-versus-optional backend field validation is unknown beyond native frontend attributes.\n\nRetry creation with the same idempotency key; mismatched payload yields IDEMPOTENCY_CONFLICT. Real school idempotency support is unknown: an adapter must implement durable deduplication and reconcile uncertain outcomes rather than blindly retrying. Reschedule checks replacement capacity before releasing old slots. A slot race returns SLOT_NO_LONGER_AVAILABLE, refreshes availability and asks for a new selection. Timeout on a future write means outcome unknown; never claim failure is proof that no booking exists.\n\nPayment-card collection is outside these contracts. Secure checkout URLs, payment confirmation, fee rounding and temporary holds require an approved contract. No production custom function was created.\n')
    write_text(ROOT/'docs/booking_system_architecture.md','# Booking system architecture\n\n'+common+'Future manual Retell tools → our authenticated API → common BookingAdapter → school system. Current code supplies only adapters, not an HTTP server or deployed tools.\n\nBestDrivingSchoolBookingAdapter: explicitly enabled date-only public GET reads; all production transaction/customer-lookup methods fail LIVE_WRITES_DISABLED without contacting the network. MockBookingAdapter: isolated in-memory synthetic slots/customer refs/bookings, verification guards, idempotent creation and atomic reschedule/cancel. No production data is seeded into mock.\n\nIntegration boundary: canonical catalog IDs → observed form product IDs (provisional) → authoritative mapping still required. Time-label normalization does not establish resource IDs or a real booking identity. Preserve separate adapter mode in every response; a mock success can never be spoken as a real school reservation.\n\nRun offline investigation assembly: `python -m src.booking.investigate`. Live read is disabled by default; use enabled=True explicitly only for approved read-only observation and disable again with enabled=False/new default instance. No credentials/env keys are created because the actual authentication scheme is not known. No `.env.example` with guessed keys is needed.\n')
    write_text(ROOT/'docs/booking_security_boundaries.md','# Booking security boundaries\n\nOnly public source/form inspection and evidenced time-only GET reads were authorized/executed. No recursive restricted-route scraper, authentication bypass, student enumeration, production write, payment or cancellation. Never log DOB, driver/permit identifiers, full customer records, cookies/tokens, card data or raw exceptions. Network observation artifacts contain public field names/product option values and time-only data.\n\nFuture API authentication, customer verification, access scope, CSRF and cancellation authority must come from school contracts. Do not transplant browser cookies or submit a native form as an undocumented API. Mask operational debug logs to timestamp/operation/package/location/date/result/error_code/latency; no raw request bodies. Mock verification tokens are synthetic fixtures, not a production authentication model.\n\nLive writes are disabled in code. No guessed endpoints, credentials or request parameters. Follow no redirects from the known GET endpoints. Reject malformed responses instead of exposing raw payloads. Revalidate dates, capacity, timezone, prerequisites and approved policy at write time in the later integration.\n')
    write_text(ROOT/'knowledge/retell_support/booking_persona_data_requirements.md','# Booking persona data requirements\n\nManual planning only. Receive intent, program/course/canonical package ID/name, sourced package price, school/regulatory prerequisite status, preferred location/date/time and selected returned slot. Do not confuse canonical IDs with provisional public form product IDs. Location IDs and stable live slot IDs are not confirmed.\n\nAsk only necessary unanswered preferences. Student/caller name and phone/email are caller-provided inputs if later required; verified customer_ref and appointment_id must come from an approved backend. DOB/permit numbers and payment-card information should remain in secure official enrollment/checkout flows. Actual verification and required fields need business approval. Multi-session choices may require several appointments; frontend row count alone is not confirmed remaining-hours accounting.\n\nProposed operational variables: location_id/location_name, selected_slot_id, verified_customer_ref, verification_status, appointment_id, booking_status, booking_version, adapter_mode and last_tool_result. Preserve existing program/course/package/price and caller preference proposals. No Retell variables or workflow nodes were configured. Mock results are for testing only and must be identified as mock in every answer.\n')
    write_text(ROOT/'knowledge/retell_support/booking_state_reference.md','# Booking state reference\n\n`availability_checked` → `slot_selected` → `booking_pending` → `booking_confirmed` only after explicit backend success and a returned appointment identifier. Any negative/uncertain result stays `booking_failed` or pending reconciliation; never say “You’re booked” from a selected slot, a submitted request or a timeout. Availability reads always report booking_confirmed=false. Mock success must be described as a mock reservation only.\n\nSlot race: return SLOT_NO_LONGER_AVAILABLE → refresh availability → offer new returned slots → customer selects again. Retry creation with the same idempotency key; real school idempotency is unverified. For reschedule, verify known booking/customer, check new slots, receive selection and update atomically before confirmation. Cancellation requires approved policy and verification; refunds are not implied. Production cancellation currently requires human escalation.\n\nNormalized errors: TIMEOUT, INVALID_PACKAGE, INVALID_LOCATION, SLOT_NO_LONGER_AVAILABLE, BACKEND_UNAVAILABLE, AUTHENTICATION_FAILURE, VALIDATION_ERROR, UNKNOWN_SERVER_ERROR, IDEMPOTENCY_CONFLICT, LIVE_DISABLED and LIVE_WRITES_DISABLED. Provide safe messages without internal details. These are our interface semantics, not observed school error enums.\n')


if __name__=='__main__':main()
